services:
  - type: web
    name: sleep-apnea-detector
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: gunicorn app:app --timeout 90 --workers 1 --threads 2
    autoDeploy: true
